/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import view.Login;


/**
 *
 * @author Acer
 */
public class CrearUsuario extends javax.swing.JFrame {

    ;
    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        setimages(volverLbl, "src/resources/Volver.png");
    }
    private void setimages(JLabel labelname, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        txtCreateUser = new javax.swing.JTextField();
        txtCreatePass = new javax.swing.JTextField();
        txtCreatePS = new javax.swing.JTextField();
        BtnCrear = new Clases.PanelRound();
        LblCrear = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        panelRound2 = new Clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        panelRound4 = new Clases.PanelRound();
        volverLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 236, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(165, 216, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        txtCreateUser.setBackground(new java.awt.Color(165, 216, 255));
        txtCreateUser.setForeground(new java.awt.Color(0, 102, 255));
        txtCreateUser.setText("Nombre de Usuario");
        txtCreateUser.setBorder(null);
        txtCreateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCreateUserMousePressed(evt);
            }
        });
        txtCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateUserActionPerformed(evt);
            }
        });

        txtCreatePass.setBackground(new java.awt.Color(165, 216, 255));
        txtCreatePass.setForeground(new java.awt.Color(0, 102, 255));
        txtCreatePass.setText("Contraseña");
        txtCreatePass.setBorder(null);
        txtCreatePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCreatePassMousePressed(evt);
            }
        });

        txtCreatePS.setBackground(new java.awt.Color(165, 216, 255));
        txtCreatePS.setForeground(new java.awt.Color(0, 102, 255));
        txtCreatePS.setText("Palabra de Seguridad");
        txtCreatePS.setBorder(null);
        txtCreatePS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCreatePSMousePressed(evt);
            }
        });
        txtCreatePS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreatePSActionPerformed(evt);
            }
        });

        BtnCrear.setBackground(new java.awt.Color(77, 171, 247));
        BtnCrear.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrear.setRoundBottomLeft(50);
        BtnCrear.setRoundBottomRight(50);
        BtnCrear.setRoundTopLeft(50);
        BtnCrear.setRoundTopRight(50);

        LblCrear.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        LblCrear.setForeground(new java.awt.Color(255, 255, 255));
        LblCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCrear.setText("CREAA");
        LblCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblCrearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnCrearLayout = new javax.swing.GroupLayout(BtnCrear);
        BtnCrear.setLayout(BtnCrearLayout);
        BtnCrearLayout.setHorizontalGroup(
            BtnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );
        BtnCrearLayout.setVerticalGroup(
            BtnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(0, 102, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 255));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 255));

        jSeparator4.setBackground(new java.awt.Color(0, 102, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(BtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtCreatePass, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtCreatePS, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator4))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCreatePass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCreatePS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(BtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, 310));

        jPanel2.setBackground(new java.awt.Color(233, 236, 239));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        panelRound2.setBackground(new java.awt.Color(234, 221, 215));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR USUARIO");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 420, 70));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(100);
        panelRound4.setRoundBottomRight(100);
        panelRound4.setRoundTopLeft(100);
        panelRound4.setRoundTopRight(100);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverLbl.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        volverLbl.setForeground(new java.awt.Color(165, 216, 255));
        volverLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volverLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverLblMouseClicked(evt);
            }
        });
        panelRound4.add(volverLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverLblMouseClicked
        Login ventana = new Login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverLblMouseClicked

    private void LblCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCrearMouseExited
        BtnCrear.setBackground(new Color(77,171,247));
    }//GEN-LAST:event_LblCrearMouseExited

    private void LblCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCrearMouseEntered
        BtnCrear.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_LblCrearMouseEntered

    private void LblCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCrearMouseClicked
        String user = txtCreateUser.getText().trim();
        String pass = txtCreatePass.getText().trim();
        String palSeguridad = txtCreatePS.getText().trim();
        
        
        

        if (user.equals("Nombre de Usuario") || pass.equals("Contraseña") || palSeguridad.equals("Palabra de Seguridad")) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
            return;
        }
    }//GEN-LAST:event_LblCrearMouseClicked

    private void txtCreatePSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreatePSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreatePSActionPerformed

    private void txtCreatePSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCreatePSMousePressed
        if (txtCreatePS.getText().equals("Palabra de Seguridad")){
            txtCreatePS.setText("");
        }
        if(String.valueOf(txtCreatePass.getText()).isEmpty()){
            txtCreatePass.setText("Contraseña");
        }
        if(String.valueOf(txtCreateUser.getText()).isEmpty()){
            txtCreateUser.setText("Nombre de usuario");
        }
    }//GEN-LAST:event_txtCreatePSMousePressed

    private void txtCreatePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCreatePassMousePressed
        if(String.valueOf(txtCreatePass.getText()).equals("Contraseña")){
            txtCreatePass.setText("");
        }
        if(txtCreateUser.getText().isEmpty()){
            txtCreateUser.setText("Nombre de Usuario");
        }
        if(txtCreatePS.getText().isEmpty()){
            txtCreatePS.setText("Palabra de Seguridad");
        }
    }//GEN-LAST:event_txtCreatePassMousePressed

    private void txtCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateUserActionPerformed

    private void txtCreateUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCreateUserMousePressed
        if (txtCreateUser.getText().equals("Nombre de Usuario")){
            txtCreateUser.setText("");
        }
        if(String.valueOf(txtCreatePass.getText()).isEmpty()){
            txtCreatePass.setText("Contraseña");
        }
        if(String.valueOf(txtCreatePS.getText()).isEmpty()){
            txtCreatePS.setText("Palabra de Seguridad");
        }
    }//GEN-LAST:event_txtCreateUserMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Clases.PanelRound BtnCrear;
    private javax.swing.JLabel LblCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound2;
    private Clases.PanelRound panelRound4;
    private javax.swing.JTextField txtCreatePS;
    private javax.swing.JTextField txtCreatePass;
    private javax.swing.JTextField txtCreateUser;
    private javax.swing.JLabel volverLbl;
    // End of variables declaration//GEN-END:variables
}
