/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Acer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setimages(ImagenLogo, "src/resources/JAY wallet.png");
        setimages(UserLbl, "src/resources/Usuario.png");
        setimages(PassLbl, "src/resources/Contraseña.png");
        String nombre;
        nombre = txtuser.getText();
    }
    
    private void setimages(JLabel labelname, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        ImagenLogo = new javax.swing.JLabel();
        UserLbl = new javax.swing.JLabel();
        PassLbl = new javax.swing.JLabel();
        BtnLogin = new Clases.PanelRound();
        LoginBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        BtnCrearU = new Clases.PanelRound();
        CrearULbl1 = new javax.swing.JLabel();
        BtnRestablecer = new Clases.PanelRound();
        RestablecerLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 236, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(233, 236, 239));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 50, 40));

        panelRound1.setBackground(new java.awt.Color(165, 216, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        txtuser.setBackground(new java.awt.Color(165, 216, 255));
        txtuser.setForeground(new java.awt.Color(0, 102, 255));
        txtuser.setText("Nombre");
        txtuser.setBorder(null);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        txtpass.setBackground(new java.awt.Color(165, 216, 255));
        txtpass.setForeground(new java.awt.Color(0, 102, 255));
        txtpass.setText("********");
        txtpass.setBorder(null);
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        ImagenLogo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ImagenLogo.setForeground(new java.awt.Color(234, 230, 255));
        ImagenLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenLogo.setText("imagen logotipo");

        UserLbl.setForeground(new java.awt.Color(234, 230, 255));
        UserLbl.setText("USER");

        PassLbl.setForeground(new java.awt.Color(234, 230, 255));
        PassLbl.setText("PASS");

        BtnLogin.setBackground(new java.awt.Color(77, 171, 247));
        BtnLogin.setRoundBottomLeft(50);
        BtnLogin.setRoundBottomRight(50);
        BtnLogin.setRoundTopLeft(50);
        BtnLogin.setRoundTopRight(50);

        LoginBtn.setBackground(new java.awt.Color(77, 171, 247));
        LoginBtn.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginBtn.setText("Log in");
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnLoginLayout = new javax.swing.GroupLayout(BtnLogin);
        BtnLogin.setLayout(BtnLoginLayout);
        BtnLoginLayout.setHorizontalGroup(
            BtnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        BtnLoginLayout.setVerticalGroup(
            BtnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator2.setBackground(new java.awt.Color(0, 102, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 255));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(PassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(UserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 362, 326));

        BtnCrearU.setBackground(new java.awt.Color(234, 221, 215));
        BtnCrearU.setRoundBottomLeft(40);
        BtnCrearU.setRoundBottomRight(40);
        BtnCrearU.setRoundTopLeft(40);
        BtnCrearU.setRoundTopRight(40);

        CrearULbl1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        CrearULbl1.setForeground(new java.awt.Color(60, 63, 65));
        CrearULbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearULbl1.setText("Crear Usuario");
        CrearULbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearULbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearULbl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearULbl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearULbl1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnCrearULayout = new javax.swing.GroupLayout(BtnCrearU);
        BtnCrearU.setLayout(BtnCrearULayout);
        BtnCrearULayout.setHorizontalGroup(
            BtnCrearULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnCrearULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearULbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        BtnCrearULayout.setVerticalGroup(
            BtnCrearULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnCrearULayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CrearULbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(BtnCrearU, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 37));

        BtnRestablecer.setBackground(new java.awt.Color(234, 221, 215));
        BtnRestablecer.setRoundBottomLeft(40);
        BtnRestablecer.setRoundBottomRight(40);
        BtnRestablecer.setRoundTopLeft(40);
        BtnRestablecer.setRoundTopRight(40);

        RestablecerLbl.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        RestablecerLbl.setForeground(new java.awt.Color(60, 63, 65));
        RestablecerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RestablecerLbl.setText("Restablecer contraseña");
        RestablecerLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestablecerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestablecerLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestablecerLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestablecerLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnRestablecerLayout = new javax.swing.GroupLayout(BtnRestablecer);
        BtnRestablecer.setLayout(BtnRestablecerLayout);
        BtnRestablecerLayout.setHorizontalGroup(
            BtnRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnRestablecerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RestablecerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnRestablecerLayout.setVerticalGroup(
            BtnRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RestablecerLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanel1.add(BtnRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestablecerLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestablecerLblMouseEntered
        // TODO add your handling code here:
        BtnRestablecer.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_RestablecerLblMouseEntered

    private void RestablecerLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestablecerLblMouseExited
        // TODO add your handling code here:
        BtnRestablecer.setBackground(new Color(234,221,215));
    }//GEN-LAST:event_RestablecerLblMouseExited

    private void RestablecerLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestablecerLblMouseClicked
        ConfirmacionRestaurar ventana = new ConfirmacionRestaurar();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RestablecerLblMouseClicked

    private void CrearULbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearULbl1MouseClicked
        CrearUsuario ventana = new CrearUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CrearULbl1MouseClicked

    private void CrearULbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearULbl1MouseEntered
        BtnCrearU.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_CrearULbl1MouseEntered

    private void CrearULbl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearULbl1MouseExited
        BtnCrearU.setBackground(new Color(234,221,215));
    }//GEN-LAST:event_CrearULbl1MouseExited

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited
        BtnLogin.setBackground(new Color(77,171,247));

    }//GEN-LAST:event_LoginBtnMouseExited

         //Color del boton
    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered
        BtnLogin.setBackground(new Color(0,153,255));

    }//GEN-LAST:event_LoginBtnMouseEntered

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked
        //Boton Login

        String usuario = txtuser.getText().trim();
        String contraseña = new String(txtpass.getPassword()).trim();

        if (usuario.equals("Nombre") || contraseña.equals("********")) {
            JOptionPane.showMessageDialog(null, "Por favor, complete ambos campos.");
            return;
        }
        if (usuario.equals("Jaider")&& contraseña.equals("12345")) {
            ConfiUsuario acceso = new ConfiUsuario();
            acceso.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
        }
    }//GEN-LAST:event_LoginBtnMouseClicked

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Nombre");
        }
        if(String.valueOf(txtpass.getPassword()).equals("********")){
            txtpass.setText("");
        }
    }//GEN-LAST:event_txtpassMousePressed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        if (txtuser.getText().equals("Nombre")){
            txtuser.setText("");
        }
        if(String.valueOf(txtpass.getPassword()).isEmpty()){
            txtpass.setText("********");
        }
    }//GEN-LAST:event_txtuserMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Clases.PanelRound BtnCrearU;
    private Clases.PanelRound BtnLogin;
    private Clases.PanelRound BtnRestablecer;
    private javax.swing.JLabel CrearULbl1;
    private javax.swing.JLabel ImagenLogo;
    private javax.swing.JLabel LoginBtn;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JLabel RestablecerLbl;
    private javax.swing.JLabel UserLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private Clases.PanelRound panelRound1;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
